name: Digest Summarizer

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  

jobs:
  Run_digest: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Github Issues Digest
        uses: Eclipse-Dominator/Github_Digest@bug-fixes

          
