name: Digest Summarizer

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  Create digests: 
    runs-on: ubuntu-latest

      - name: Run script
        with:
          GIT_SECRET: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd .github
          ./digest