name: Digest Summarizer

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  Run_digest: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Run script
        env:
          GIT_SECRET: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd .github
          ./digest
